#XQa9cvc-B7d4lnwByRZa9keN90-vXaN3WjBGZ7-heas build --non-interactive
name: pull_requests
on:
  workflow_dispatch:
  pull_request:
    branches: [main, dev]
jobs:
  format:
    name: formatting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: npm ci
      - run: npm run check

  lint:
    name: linting
    runs-on: ubuntu-latest

    steps:
      - run: npm ci
      - run: npm run eslint

  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm
      - run: npm ci
      - run: npm build
